name: Checkmarx SAST Scan
 
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CX_SERVER: ${{ secrets.CX_SERVER }}
  #CX_SERVER: https://checkmarx.app.medcity.net
  CX_TEAM: ${{ secrets.CX_TEAM }}
  #CX_TEAM: /CxServer/Sx/Cx/IPS/HCA/SDODevOps
  CX_USER: ${{ secrets.CX_USER }}
  CX_PASSWORD: ${{ secrets.CX_PASSWORD }}
  CX_PROJECT: "ASP-NET-CORE-APP"
  CX_PRESET: "Checkmarx Default"
  CX_HIGH: 1000
  CX_MEDIUM: 1000
  CX_LOW: 1000
  CX_INCREMENTAL: ""

jobs:
  checkmarx-cli-scan:
    name: Run Checkmarx CLI Scan
    runs-on: [self-hosted, windows, x64]
    steps:
    
    - name: Download CxCLI Zip
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
        Invoke-WebRequest -Uri https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-2020.4.4.zip -OutFile cxcli.zip
      shell: powershell
    - name: Unzip CxCLI Zip
      run: Expand-Archive -Path .\cxcli.zip -DestinationPath .\cxcli
      shell: powershell
           
    - uses: actions/checkout@v2
    - name: Run Checkmarx Scan
      #run: C:\CxConsole\runCxConsole.cmd Scan -CxServer $env:CX_SERVER -CxUser $env:CX_USER -CxPassword $env:CX_PASSWORD -ProjectName "$env:CX_TEAM/$env:GITHUB_REPOSITORY" -preset $env:CX_PRESET -LocationType folder -LocationPath $env:GITHUB_WORKSPACE -SASTHigh $env:CX_HIGH -SASTMedium $env:CX_MEDIUM -SASTLow $env:CX_LOW -ReportXML $env:GITHUB_WORKSPACE\\checkmarxResults.xml -ReportPDF $env:GITHUB_WORKSPACE\\checkmarxResults.pdf -Comment "git $env:GITHUB_REFH@$env:GITHUB_SHA" -verbose $env:CX_INCREMENTAL
      #run: C:\CxConsole\runCxConsole.cmd Scan -CxServer $env:CX_SERVER -CxUser $env:CX_USER -CxPassword $env:CX_PASSWORD -ProjectName "$env:CX_TEAM/$env:CX_PROJECT" -preset $env:CX_PRESET -LocationType folder -LocationPath $env:GITHUB_WORKSPACE -SASTHigh $env:CX_HIGH -SASTMedium $env:CX_MEDIUM -SASTLow $env:CX_LOW -ReportXML $env:GITHUB_WORKSPACE\\checkmarxResults.xml -ReportPDF $env:GITHUB_WORKSPACE\\checkmarxResults.pdf -Comment "git $env:GITHUB_REFH@$env:GITHUB_SHA" -verbose $env:CX_INCREMENTAL
      run: runCxConsole.cmd Scan -CxServer $env:CX_SERVER -CxUser $env:CX_USER -CxPassword $env:CX_PASSWORD -ProjectName "$env:CX_TEAM/$env:CX_PROJECT" -preset $env:CX_PRESET -LocationType folder -LocationPath $env:GITHUB_WORKSPACE -SASTHigh $env:CX_HIGH -SASTMedium $env:CX_MEDIUM -SASTLow $env:CX_LOW -ReportXML $env:GITHUB_WORKSPACE\\checkmarxResults.xml -ReportPDF $env:GITHUB_WORKSPACE\\checkmarxResults.pdf -Comment "git $env:GITHUB_REFH@$env:GITHUB_SHA" -verbose $env:CX_INCREMENTAL
      shell: powershell
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@master
      with:
        name: results.pdf
        path: results.pdf
    - name: Upload XML Artifact
      uses: actions/upload-artifact@master
      with:
        name: results.xml
        path: results.xml
